export const HOST = 'http://34.78.241.147/';
export const SKINS = `${HOST}api/v1/items/`; //Ready
export const CATEGORIES = `${HOST}api/v1/categories/`; // Ready
export const REGISTRATION = `${HOST}api/v1/registration/`; // Ready not visual of course
export const AUTHORIZATION = `${HOST}api/token/`; // Ready not visual of course
export const CHANGE_PASSWORD = `${HOST}api/v1/change-password/`; // Ready not visual of course
export const PER_CAB = `${HOST}api/v1/per-cab/`; // Ready
export const FRIENDS = `${HOST}api/v1/friends/`; // Ready
export const ART_MONEY = `${HOST}api/v1/art-money/`; // Ready
export const COLLECTION = `${HOST}api/v1/collection/`; // Ready
export const RESET_PASSWORD = `${HOST}api/v1/reset-password/`; //Ready not visual of course
export const INVITES = `${HOST}api/v1/invites/`; //Ready
export const REVIEWS = `${HOST}api/v1/reviews/`; //Ready
export const BASKET = `${HOST}api/v1/basket/`; //Ready
export const ACTIVATE = `${HOST}activate/`;
export const WEBHOOK = `${HOST}api/v1/webhook/`;
